In [4]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn import linear_model
from word2number import w2n

In [5]:
df=pd.read_csv('hiring.csv')
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [6]:
df.iloc[:,0]=df.iloc[:,0].fillna('zero')
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [7]:
experience_num=df.iloc[:,0].apply(w2n.word_to_num)
experience_num

0     0
1     0
2     5
3     2
4     7
5     3
6    10
7    11
Name: experience, dtype: int64

In [8]:
df.iloc[:,0]=experience_num
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0          0                    8.0                           9      50000
1          0                    8.0                           6      45000
2          5                    6.0                           7      60000
3          2                   10.0                          10      65000
4          7                    9.0                           6      70000
5          3                    7.0                          10      62000
6         10                    NaN                           7      72000
7         11                    7.0                           8      80000

In [9]:
mean_test_score=round(df.iloc[:,1].mean(),1)
mean_test_score

np.float64(7.9)

In [10]:
df.iloc[:,1]=df.iloc[:,1].fillna(mean_test_score)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0          0                    8.0                           9      50000
1          0                    8.0                           6      45000
2          5                    6.0                           7      60000
3          2                   10.0                          10      65000
4          7                    9.0                           6      70000
5          3                    7.0                          10      62000
6         10                    7.9                           7      72000
7         11                    7.0                           8      80000

In [11]:
reg=linear_model.LinearRegression()
reg.fit(df[['experience','test_score(out of 10)','interview_score(out of 10)']],df['salary($)'])

LinearRegression()

In [12]:
test_arr=np.array([[2,9,9],[5,6,7]])
reg.predict(test_arr)

C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([59864.09760915, 58255.32779028])

In [13]:
reg.coef_


array([2823.17277781, 1893.11697736, 2199.4686101 ])

In [14]:
reg.intercept_

np.float64(17384.48176636498)

In [15]:
print(2823.17277781*2+ 9*1893.11697736+9*2199.4686101+17384.48176636498 )

59864.09760912498


In [16]:
import joblib

In [17]:
joblib.dump(reg,'hiring_model')

['hiring_model']

In [18]:
model=joblib.load('hiring_model')

In [19]:
model.predict(test_arr)

C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([59864.09760915, 58255.32779028])