<a href="https://colab.research.google.com/github/irtisamsajin/ML_DL_Tutorials/blob/main/numpy/numpyTutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
np.zeros(3) # [0,0,0]

array([0., 0., 0.])

In [4]:
np.ones(3)  #[1,1,1]

array([1., 1., 1.])

In [6]:
np.arange(4) #[0,1,2,3]

array([0, 1, 2, 3])

In [7]:
np.arange(2,8,2) # arange(first,last,step)

array([2, 4, 6])

In [10]:
np.linspace(1,10,5)  #linspace(start,end, number of elements)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [11]:
np.empty(4) #empty(number of elements)  -> generates random numbers

array([4.81067779e-310, 0.00000000e+000, 2.05833592e-312, 2.14321575e-312])

In [12]:
np.ones(4,dtype=np.int32) #by default type is float 64.

array([1, 1, 1, 1], dtype=int32)

In [13]:
a=np.array([2,9,3,4,11,3,5])

In [14]:
np.sort(a)

array([ 2,  3,  3,  4,  5,  9, 11])

In [20]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
np.concatenate((a,b),axis=0) #joins the array b with array a

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [23]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
np.concatenate((a,b),axis=1) #joins the first row of array a with that of b and the remaining rows in the same manner.

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [25]:
a = np.array([[[0, 1, 2, 3],
              [4, 5, 6, 7]],

              [[0, 1, 2, 3],
              [4, 5, 6, 7]],

              [[0 ,1 ,2, 3],
              [4, 5, 6, 7]]])

In [28]:
print(a.ndim) #no of dimensions
print(a.size) #total no of elements
print(a.shape)

3
24
(3, 2, 4)


In [30]:
np.full((3,2),10)  #np.full(shape,element to be filled with)

array([[10, 10],
       [10, 10],
       [10, 10]])

In [36]:
python_list=[1,2,3,4]
np.array(python_list) #converting python list to numpy array

1


In [41]:
a=np.array([1,2,3,4,5,6,7,8])
b=a[1:3]  #b=a[start:end+1]
c=a[1:]   #from index-1 to end
d=a[:3]   #from start to index 3-1=2
print(a,b,c,d)

[1 2 3 4 5 6 7 8] [2 3] [2 3 4 5 6 7 8] [1 2 3]


In [44]:
print(a[0:7:2]) #a[start:end:step]

[1 3 5 7]


In [45]:
print(a[-4:-1]) # [5,6,7]

[5 6 7]


In [50]:
arr2D=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [53]:
print(arr2D[0:2,1:2]) #[[2],[5]]

[[2]
 [5]]


In [56]:
a=[-4,-1,-10,0,1,10,11,4,6]

In [59]:
print(np.abs(a))
print(np.exp(a))
print(np.min(a))
print(np.max(a))
print(np.sign(a))
print(np.sin(a))
print(np.log(np.array([3,4,5,6])))
print(np.sqrt(np.array([3,4,5,6,7,9])))

[ 4  1 10  0  1 10 11  4  6]
[1.83156389e-02 3.67879441e-01 4.53999298e-05 1.00000000e+00
 2.71828183e+00 2.20264658e+04 5.98741417e+04 5.45981500e+01
 4.03428793e+02]
-10
11
[-1 -1 -1  0  1  1  1  1  1]
[ 0.7568025  -0.84147098  0.54402111  0.          0.84147098 -0.54402111
 -0.99999021 -0.7568025  -0.2794155 ]
[1.09861229 1.38629436 1.60943791 1.79175947]
[1.73205081 2.         2.23606798 2.44948974 2.64575131 3.        ]


In [61]:
orgarr=np.array([1,2,3,4])
cpyarr=orgarr.copy() #only puts elements to new arr. changes in org does not affect cpy
viewarr=orgarr.view() #changes in org will change view and vice versa

In [62]:
orgarr[0]=10
print(orgarr,cpyarr,viewarr)

[10  2  3  4] [1 2 3 4] [10  2  3  4]


In [63]:
viewarr[0]=99
print(orgarr,cpyarr,viewarr)

[99  2  3  4] [1 2 3 4] [99  2  3  4]


In [68]:
#Reshaping
np1=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
np2=np1.reshape(3,4) #Reshape np1 to 3 rows and 4 col. there must be 12 elements in np1
print(np2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [69]:
np3=np1.reshape(2,3,2)
print(np3)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
